#pragma once

#include "SizeKorea-2020Doc.h"
#include "SizeKorea-2020View.h"

// CPose2ResultDialog dialog

class CPose2ResultDialog : public CDialogEx
{
	DECLARE_DYNAMIC(CPose2ResultDialog)

public:
	CPose2ResultDialog(CWnd* pParent = nullptr);   // standard constructor
	virtual ~CPose2ResultDialog();

	CSizeKorea2020View *GetView();
	CSizeKorea2020Doc *GetDocument();
	void InitDialog();

// Dialog Data
#ifdef AFX_DESIGN_TIME
	enum { IDD = IDD_POSE2_RESULT_DIALOG };
#endif

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	DECLARE_MESSAGE_MAP()
public:
	BOOL m_bPose2ShowPath1;
	CString m_Pose2Result1;
	BOOL m_bPose2ShowPath2;
	BOOL m_bPose2ShowPath3;
	BOOL m_bPose2ShowPath4;
	BOOL m_bPose2ShowPath5;
	BOOL m_bPose2ShowPath6;
	BOOL m_bPose2ShowPath7;
	BOOL m_bPose2ShowPath8;
	BOOL m_bPose2ShowPath9;
	BOOL m_bPose2ShowPath10;
	BOOL m_bPose2ShowPath11;
	BOOL m_bPose2ShowPath12;
	BOOL m_bPose2ShowPath13;
	BOOL m_bPose2ShowPath14;
	BOOL m_bPose2ShowPath15;
	BOOL m_bPose2ShowPath16;
	BOOL m_bPose2ShowPath17;
	BOOL m_bPose2ShowPath18;
	BOOL m_bPose2ShowPath19;
	BOOL m_bPose2ShowPath20;
	BOOL m_bPose2ShowPath21;
	BOOL m_bPose2ShowPath22;
	BOOL m_bPose2ShowPath23;
	BOOL m_bPose2ShowPath24;
	BOOL m_bPose2ShowPath25;
	BOOL m_bPose2ShowPath26;
	BOOL m_bPose2ShowPath27;
	BOOL m_bPose2ShowPath28;
	BOOL m_bPose2ShowPath29;
	BOOL m_bPose2ShowPath30;
	BOOL m_bPose2ShowPath31;
	BOOL m_bPose2ShowPath32;
	BOOL m_bPose2ShowPath33;
	BOOL m_bPose2ShowPath34;
	BOOL m_bPose2ShowPath35;
	BOOL m_bPose2ShowPath36;
	BOOL m_bPose2ShowPath37;
	BOOL m_bPose2ShowPath38;
	BOOL m_bPose2ShowPath39;
	BOOL m_bPose2ShowPath40;
	BOOL m_bPose2ShowPath41;
	BOOL m_bPose2ShowPath42;
	BOOL m_bPose2ShowPath43;
	BOOL m_bPose2ShowPath44;
	BOOL m_bPose2ShowPath45;
	BOOL m_bPose2ShowPath46;
	BOOL m_bPose2ShowPath47;
	BOOL m_bPose2ShowPath48;
	BOOL m_bPose2ShowPath49;
	BOOL m_bPose2ShowPath50;
	BOOL m_bPose2ShowPath51;
	BOOL m_bPose2ShowPath52;
	BOOL m_bPose2ShowPath53;
	BOOL m_bPose2ShowPath54;
	BOOL m_bPose2ShowPath55;
	BOOL m_bPose2ShowPath56;
	BOOL m_bPose2ShowPath57;
	BOOL m_bPose2ShowPath58;
	BOOL m_bPose2ShowPath59;
	BOOL m_bPose2ShowPath60;
	BOOL m_bPose2ShowPath61;
	BOOL m_bPose2ShowPath62;
	BOOL m_bPose2ShowPath63;
	BOOL m_bPose2ShowPath64;
	BOOL m_bPose2ShowPath65;
	BOOL m_bPose2ShowPath66;
	BOOL m_bPose2ShowPath67;
	BOOL m_bPose2ShowPath68;
	BOOL m_bPose2ShowPath69;
	BOOL m_bPose2ShowPath70;
	BOOL m_bPose2ShowPath71;
	BOOL m_bPose2ShowPath72;
	BOOL m_bPose2ShowPath73;
	BOOL m_bPose2ShowPath74;
	BOOL m_bPose2ShowPath75;
	BOOL m_bPose2ShowPath76;
	BOOL m_bPose2ShowPath77;
	BOOL m_bPose2ShowPath78;
	BOOL m_bPose2ShowPath79;
	CString m_Pose2Result2;
	CString m_Pose2Result3;
	CString m_Pose2Result4;
	CString m_Pose2Result5;
	CString m_Pose2Result6;
	CString m_Pose2Result7;
	CString m_Pose2Result8;
	CString m_Pose2Result9;
	CString m_Pose2Result10;
	CString m_Pose2Result11;
	CString m_Pose2Result12;
	CString m_Pose2Result13;
	CString m_Pose2Result14;
	CString m_Pose2Result15;
	CString m_Pose2Result16;
	CString m_Pose2Result17;
	CString m_Pose2Result18;
	CString m_Pose2Result19;
	CString m_Pose2Result20;
	CString m_Pose2Result21;
	CString m_Pose2Result22;
	CString m_Pose2Result23;
	CString m_Pose2Result24;
	CString m_Pose2Result25;
	CString m_Pose2Result26;
	CString m_Pose2Result27;
	CString m_Pose2Result28;
	CString m_Pose2Result29;
	CString m_Pose2Result30;
	CString m_Pose2Result31;
	CString m_Pose2Result32;
	CString m_Pose2Result33;
	CString m_Pose2Result34;
	CString m_Pose2Result35;
	CString m_Pose2Result36;
	CString m_Pose2Result37;
	CString m_Pose2Result38;
	CString m_Pose2Result39;
	CString m_Pose2Result40;
	CString m_Pose2Result41;
	CString m_Pose2Result42;
	CString m_Pose2Result43;
	CString m_Pose2Result44;
	CString m_Pose2Result45;
	CString m_Pose2Result46;
	CString m_Pose2Result47;
	CString m_Pose2Result48;
	CString m_Pose2Result49;
	CString m_Pose2Result50;
	CString m_Pose2Result51;
	CString m_Pose2Result52;
	CString m_Pose2Result53;
	CString m_Pose2Result54;
	CString m_Pose2Result55;
	CString m_Pose2Result56;
	CString m_Pose2Result57;
	CString m_Pose2Result58;
	CString m_Pose2Result59;
	CString m_Pose2Result60;
	CString m_Pose2Result61;
	CString m_Pose2Result62;
	CString m_Pose2Result63;
	CString m_Pose2Result64;
	CString m_Pose2Result65;
	CString m_Pose2Result66;
	CString m_Pose2Result67;
	CString m_Pose2Result68;
	CString m_Pose2Result69;
	CString m_Pose2Result70;
	CString m_Pose2Result71;
	CString m_Pose2Result72;
	CString m_Pose2Result73;
	CString m_Pose2Result74;
	CString m_Pose2Result75;
	CString m_Pose2Result76;
	CString m_Pose2Result77;
	CString m_Pose2Result78;
	CString m_Pose2Result79;
	afx_msg void OnBnClickedPose2ShowPath1();
	afx_msg void OnBnClickedPose2ShowPath2();
	afx_msg void OnBnClickedPose2ShowPath3();
	afx_msg void OnBnClickedPose2ShowPath4();
	afx_msg void OnBnClickedPose2ShowPath5();
	afx_msg void OnBnClickedPose2ShowPath6();
	afx_msg void OnBnClickedPose2ShowPath7();
	afx_msg void OnBnClickedPose2ShowPath8();
	afx_msg void OnBnClickedPose2ShowPath9();
	afx_msg void OnBnClickedPose2ShowPath10();
	afx_msg void OnBnClickedPose2ShowPath11();
	afx_msg void OnBnClickedPose2ShowPath12();
	afx_msg void OnBnClickedPose2ShowPath13();
	afx_msg void OnBnClickedPose2ShowPath14();
	afx_msg void OnBnClickedPose2ShowPath15();
	afx_msg void OnBnClickedPose2ShowPath16();
	afx_msg void OnBnClickedPose2ShowPath17();
	afx_msg void OnBnClickedPose2ShowPath18();
	afx_msg void OnBnClickedPose2ShowPath19();
	afx_msg void OnBnClickedPose2ShowPath20();
	afx_msg void OnBnClickedPose2ShowPath21();
	afx_msg void OnBnClickedPose2ShowPath22();
	afx_msg void OnBnClickedPose2ShowPath23();
	afx_msg void OnBnClickedPose2ShowPath24();
	afx_msg void OnBnClickedPose2ShowPath25();
	afx_msg void OnBnClickedPose2ShowPath26();
	afx_msg void OnBnClickedPose2ShowPath27();
	afx_msg void OnBnClickedPose2ShowPath28();
	afx_msg void OnBnClickedPose2ShowPath29();
	afx_msg void OnBnClickedPose2ShowPath30();
	afx_msg void OnBnClickedPose2ShowPath31();
	afx_msg void OnBnClickedPose2ShowPath32();
	afx_msg void OnBnClickedPose2ShowPath33();
	afx_msg void OnBnClickedPose2ShowPath34();
	afx_msg void OnBnClickedPose2ShowPath35();
	afx_msg void OnBnClickedPose2ShowPath36();
	afx_msg void OnBnClickedPose2ShowPath37();
	afx_msg void OnBnClickedPose2ShowPath38();
	afx_msg void OnBnClickedPose2ShowPath39();
	afx_msg void OnBnClickedPose2ShowPath40();
	afx_msg void OnBnClickedPose2ShowPath41();
	afx_msg void OnBnClickedPose2ShowPath42();
	afx_msg void OnBnClickedPose2ShowPath43();
	afx_msg void OnBnClickedPose2ShowPath44();
	afx_msg void OnBnClickedPose2ShowPath45();
	afx_msg void OnBnClickedPose2ShowPath46();
	afx_msg void OnBnClickedPose2ShowPath47();
	afx_msg void OnBnClickedPose2ShowPath48();
	afx_msg void OnBnClickedPose2ShowPath49();
	afx_msg void OnBnClickedPose2ShowPath50();
	afx_msg void OnBnClickedPose2ShowPath51();
	afx_msg void OnBnClickedPose2ShowPath52();
	afx_msg void OnBnClickedPose2ShowPath53();
	afx_msg void OnBnClickedPose2ShowPath54();
	afx_msg void OnBnClickedPose2ShowPath55();
	afx_msg void OnBnClickedPose2ShowPath56();
	afx_msg void OnBnClickedPose2ShowPath57();
	afx_msg void OnBnClickedPose2ShowPath58();
	afx_msg void OnBnClickedPose2ShowPath59();
	afx_msg void OnBnClickedPose2ShowPath60();
	afx_msg void OnBnClickedPose2ShowPath61();
	afx_msg void OnBnClickedPose2ShowPath62();
	afx_msg void OnBnClickedPose2ShowPath63();
	afx_msg void OnBnClickedPose2ShowPath64();
	afx_msg void OnBnClickedPose2ShowPath65();
	afx_msg void OnBnClickedPose2ShowPath66();
	afx_msg void OnBnClickedPose2ShowPath67();
	afx_msg void OnBnClickedPose2ShowPath68();
	afx_msg void OnBnClickedPose2ShowPath69();
	afx_msg void OnBnClickedPose2ShowPath70();
	afx_msg void OnBnClickedPose2ShowPath71();
	afx_msg void OnBnClickedPose2ShowPath72();
	afx_msg void OnBnClickedPose2ShowPath73();
	afx_msg void OnBnClickedPose2ShowPath74();
	afx_msg void OnBnClickedPose2ShowPath75();
	afx_msg void OnBnClickedPose2ShowPath76();
	afx_msg void OnBnClickedPose2ShowPath77();
	afx_msg void OnBnClickedPose2ShowPath78();
	afx_msg void OnBnClickedPose2ShowPath79();
	afx_msg void OnBnClickedPose2ShowPathAll();
	afx_msg void OnBnClickedPose2ShowPathNone();
	afx_msg void OnBnClickedPose2ExportResult();
};
