#ifndef _GFONT_H
#define _GFONR_H
//
//#include <windows.h>
//#include <gl\gl.h>
//
//class GFont
//{
//public:
//	HDC hdc;
//	GFont( char* type, int height, int weight, DWORD italic );
//	GFont();
//	~GFont();
//	GFont *font;
//	GLuint base;
//	int widths[256];
//	int height;
//	void FontCreate( HDC hdc, const char *typeface, int height, int weight, DWORD italic );
//	void FontDestroy();
//	void FontPrintf(int x, int y, int align, const char *format, ...);
//	void FontPuts(int x, int y, const char *s);
//	void drawTitle();
//};

#endif // _GFONT_H









