#pragma once

#define RESULT_NUM_POSE1 65

// 키
#define POSE1_MEASURE_HEIGHT 0

// 눈높이
#define POSE1_MEASURE_EYE_LEVEL 1

// 턱끝높이
#define POSE1_MEASURE_JAW_LEVEL 2

// 목뒤높이
#define POSE1_MEASURE_NECK_BACK_LEVEL 3

// 목옆높이
#define POSE1_MEASURE_NECK_SIDE_LEVEL 4

// 목앞높이
#define POSE1_MEASURE_NECK_FRONT_LEVEL 5

// 어깨높이
#define POSE1_MEASURE_SHOULDER_LEVEL 6

// 어깨가쪽높이
#define POSE1_MEASURE_SHOULDERSIDE_LEVEL 7

// 겨드랑높이
#define POSE1_MEASURE_ARMPIT_LEVEL 8

// 젖가슴높이
#define POSE1_MEASURE_BP_LEVEL 9

// 젖가슴아래높이
#define POSE1_MEASURE_UNDERBUST_LEVEL 10

// 미드리프높이
#define POSE1_MEASURE_MIDRIFF_LEVEL 11

// 허리높이
#define POSE1_MEASURE_WAIST_LEVEL 12

// 배꼽수준허리높이
#define POSE1_MEASURE_NAVEL_LEVEL 13

// 배높이
#define POSE1_MEASURE_STOMACH_EXTRUDE_LEVEL 14

// Upper-hip 높이
#define POSE1_MEASURE_UPPERHIP_LEVEL 15

// Top-hip 높이
#define POSE1_MEASURE_TOPHIP_LEVEL 16

// 엉덩이높이
#define POSE1_MEASURE_HIP_EXTRUDE_LEVEL 17

// 샅높이
#define POSE1_MEASURE_CROTCH_LEVEL 18

// 볼기고랑높이
#define POSE1_MEASURE_UNDERHIP_LEVEL 19

// 무릎뼈가운데높이
#define POSE1_MEASURE_KNEE_MID_LEVEL 20

// 무릎높이
#define POSE1_MEASURE_KNEE_LEVEL 21

// 장딴지높이
#define POSE1_MEASURE_CALF_EXTRUDE_LEVEL 22

// 가쪽복사높이
#define POSE1_MEASURE_ANKLE_LEVEL 23

// 손끝높이
#define POSE1_MEASURE_HAND_LEVEL 24


// 어깨길이
#define POSE1_MEASURE_SHOULDER_LENGTH 25

// 어깨가쪽길이
#define POSE1_MEASURE_SHOULDERSIDE_LENGTH 26

// 어깨사이길이
#define POSE1_MEASURE_BTWN_SHOULDER_LENGTH 27

// 어깨가쪽사이길이
#define POSE1_MEASURE_BTWN_SHOULDERSIDE_LENGTH 28

// 목뒤어깨길이
#define POSE1_MEASURE_BNECK_SHOULDER_LENGTH 29

// 목뒤어깨가쪽길이
#define POSE1_MEASURE_BNECK_SHOULDERSIDE_LENGTH 30

// 목뒤어깨사이길이
#define POSE1_MEASURE_BTWN_BNECK_SHOULDER_LENGTH 31

// 겨드랑뒤벽사이길이
#define POSE1_MEASURE_ARMPITWALL_BACK_LENGTH 32

// 겨드랑뒤접힘사이길이
#define POSE1_MEASURE_ARMPITFOLD_BACK_LENGTH 33

// 겨드랑앞벽사이길이
#define POSE1_MEASURE_ARMPITWALL_FRONT_LENGTH 34

// 겨드랑앞접힘사이길이
#define POSE1_MEASURE_ARMPITFOLD_FRONT_LENGTH 35

// 젖꼭지수평길이
#define POSE1_MEASURE_BP_LENGTH 36

// 겨드랑앞뒤접힘점사이길이
#define POSE1_MEASURE_ARMPITWALL_FRONT_BACK_LENGTH 37

// 앞중심길이
#define POSE1_MEASURE_CENTER_FRONT_TO_WAIST_LENGTH 38

// 배꼽수준앞중심길이
#define POSE1_MEASURE_CENTER_FRONT_TO_NAVEL_LENGTH 39

// 목옆젖꼭지길이
#define POSE1_MEASURE_SNECK_BP_LENGTH 40

// 목옆(젖꼭지)허리둘레선길이
#define POSE1_MEASURE_SNECK_BP_WAIST_LENGTH 41

// 목뒤젖꼭지길이
#define POSE1_MEASURE_BNECK_BP_LENGTH 42

// 목뒤젖꼭지허리둘레선길이
#define POSE1_MEASURE_BNECK_BP_WAIST_LENGTH 43

// 목뒤등뼈위겨드랑수준길이
#define POSE1_MEASURE_BNECK_ARMPIT_LEVEL_LENGTH 44

// 목옆뒤허리둘레선길이
#define POSE1_MEASURE_SNECK_BWAIST_LEVEL_LENGTH 45

// 등길이
#define POSE1_MEASURE_BNECK_BWAIST_LENGTH 46

// 배꼽수준등길이
#define POSE1_MEASURE_BNECK_BNAVEL_LENGTH 47

// 목뒤오금길이
#define POSE1_MEASURE_BNECK_BWAIST_HIPEXTRUDE_POPLITEUS_LENGTH 48

// 총길이
#define POSE1_MEASURE_BACK_LENGTH 49


// 위팔길이(어깨점)
#define POSE1_MEASURE_SHOULDER_ELBOW_LENGTH 50

// 위팔길이(어깨가쪽점)
#define POSE1_MEASURE_SHOULDERSIDE_ELBOW_LENGTH 51

// 팔길이(어깨점)
#define POSE1_MEASURE_SHOULDER_ELBOW_WRIST_LENGTH 52

// 팔길이(어깨가쪽점)
#define POSE1_MEASURE_SHOULDERSIDE_ELBOW_WRIST_LENGTH 53

// 몸통수직길이
#define POSE1_MEASURE_TORSO_LENGTH 54

// 엉덩이수직길이
#define POSE1_MEASURE_HIP_LENGTH 55

// 목뒤손목안쪽길이(팔내린)
#define POSE1_MEASURE_BNECK_SHOULDER_WRIST_LENGTH 56

// 넙다리직선길이
#define POSE1_MEASURE_UNDERHIP_POPLITEUS_LENGTH 57



// 벽면배돌출두께
#define POSE1_MEASURE_STOMACH_HIP_DEPTH 58

// 벽면가슴두께
#define POSE1_MEASURE_BUST_DEPTH 59

// 벽면몸통두께
#define POSE1_MEASURE_TORSO_DEPTH 60



// 오른쪽어깨가쪽경사각
#define POSE1_MEASURE_SHOULDERSIDE_RIGHT_ANGLE 61

// 왼쪽어깨가쪽경사각
#define POSE1_MEASURE_SHOULDERSIDE_LEFT_ANGLE 62

// 오른쪽어깨경사각
#define POSE1_MEASURE_SHOULDER_RIGHT_ANGLE 63

// 왼쪽어깨경사각
#define POSE1_MEASURE_SHOULDER_LEFT_ANGLE 64
