#pragma once

#define NEW_RESULT_NUM_POSE2 79

// 1 목밑둘레
#define POSE2_MEASURE_NECK_BACK_CIRC 0

// 2 가슴둘레
#define POSE2_MEASURE_BUST_CIRC 1

// 3 젖가슴둘레
#define POSE2_MEASURE_CONVEX_BP_CIRC 2

// 4 젖가슴둘레(체표를 따르는)
#define POSE2_MEASURE_BP_CIRC 3

// 5 젖가슴아래둘레
#define POSE2_MEASURE_UNDERBUST_CIRC 4

// 6 미드리프둘레
#define POSE2_MEASURE_MIDRIFF_CIRC 5

// 7 허리둘레
#define POSE2_MEASURE_WAIST_CIRC 6

// 8 배꼽수준허리둘레
#define POSE2_MEASURE_NAVEL_CIRC 7

// 9 배둘레
#define POSE2_MEASURE_STOMACH_CIRC 8

// 10 Upper-hip 둘레
#define POSE2_MEASURE_UPPERHIP_CIRC 9

// 11 Top-hip 둘레
#define POSE2_MEASURE_TOPHIP_CIRC 10

// 12 엉덩이둘레(다리벌린)
#define POSE2_MEASURE_HIP_CIRC 11

// 13 몸통세로둘레
#define POSE2_MEASURE_TORSO_CIRC 12

// 14 목밑뒤길이
#define POSE2_MEASURE_NECK_BACK_LENGTH 13

// 15 편위팔둘레
#define POSE2_MEASURE_UPPERARM_CIRC 14

// 16 편팔꿈치둘레
#define POSE2_MEASURE_ELBOW_CIRC 15

// 17 손목둘레
#define POSE2_MEASURE_WRIST_CIRC 16

// 18 넙다리둘레
#define POSE2_MEASURE_UNDERHIP_CIRC 17

// 19 넙다리중간둘레
#define POSE2_MEASURE_THIGH_CIRC 18

// 20 무릎둘레
#define POSE2_MEASURE_KNEE_CIRC 19

// 21 무릎아래둘레
#define POSE2_MEASURE_UNDERKNEE_CIRC 20

// 22 장딴지최대둘레
#define POSE2_MEASURE_MAX_CALF_EXTRUDE_CIRC 21

// 23 종아리최소둘레
#define POSE2_MEASURE_UNDERCALF_CIRC 22

// 24 발목최대둘레
#define POSE2_MEASURE_MAX_ANKLE_CIRC 23

// 25 목둘레
#define POSE2_MEASURE_NECK_THYROID_CIRC 24

// 26 겨드랑둘레(어깨점)
#define POSE2_MEASURE_ARMPIT_SHOULDER_CIRC 25

// 27 겨드랑둘레(어깨가쪽둘레)
#define POSE2_MEASURE_ARMPIT_SHOULDERSIDE_CIRC 26

// 28 가쪽복사수평둘레
#define POSE2_MEASURE_ANKLE_CIRC 27

// 29 장딴지둘레
#define POSE2_MEASURE_CALF_EXTRUDE_CIRC 28

// 30 샅앞길이
#define POSE2_MEASURE_CROTCH_FRONT_LENGTH 29

// 31 샅뒤길이
#define POSE2_MEASURE_CROTCH_BACK_LENGTH 30

// 32 샅앞뒤길이
#define POSE2_MEASURE_CROTCH_LENGTH 31

// 33 배꼽수준샅앞뒤길이
#define POSE2_MEASURE_NAVEL_CROTCH_LENGTH 32

// 34 몸통옆길이
#define POSE2_MEASURE_TORSO_SIDE_LENGTH 33

// 35 목두께
#define POSE2_MEASURE_NECK_DEPTH 34

// 36 겨드랑두께
#define POSE2_MEASURE_ARMPIT_DEPTH 35

// 37 가슴두께
#define POSE2_MEASURE_BUST_DEPTH 36

// 38 가슴두께(정중면)
#define POSE2_MEASURE_BUST_CENTER_DEPTH 37

// 39 젖가슴두께
#define POSE2_MEASURE_BP_DEPTH 38

// 40 젖가슴아래두께
#define POSE2_MEASURE_UNDERBUST_DEPTH 39

// 41 허리두께
#define POSE2_MEASURE_WAIST_DEPTH 40

// 42 허리두께(정중면)
#define POSE2_MEASURE_WAIST_CENTER_DEPTH 41

// 43 배꼽수준허리두께
#define POSE2_MEASURE_NAVEL_WAIST_DEPTH 42

// 44 배두께
#define POSE2_MEASURE_STOMACH_DEPTH 43

// 45 엉덩이두께
#define POSE2_MEASURE_HIP_DEPTH 44

// 46 넙다리두께
#define POSE2_MEASURE_UNDERHIP_DEPTH 45

// 47 넙다리중간두께
#define POSE2_MEASURE_THIGH_DEPTH 46

// 48 무릎두께
#define POSE2_MEASURE_KNEE_DEPTH 47

// 49 무릎아래두께
#define POSE2_MEASURE_UNDERKNEE_DEPTH 48

// 50 장딴지두께
#define POSE2_MEASURE_CALF_DEPTH 49

// 51 종아리아래두께
#define POSE2_MEASURE_UNDERCALF_DEPTH 50

// 52 위팔두께
#define POSE2_MEASURE_UPPERARM_DEPTH 51

// 53 팔꿈치두께
#define POSE2_MEASURE_ELBOW_DEPTH 52

// 54 손목두께
#define POSE2_MEASURE_WRIST_DEPTH 53

// 55 목너비
#define POSE2_MEASURE_NECK_WIDTH 54

// 56 목밑너비
#define POSE2_MEASURE_NECK_BACK_WIDTH 55

// 57 가슴너비
#define POSE2_MEASURE_BUST_WIDTH 56

// 58 젖가슴너비
#define POSE2_MEASURE_BP_WIDTH 57

// 59 젖가슴아래너비
#define POSE2_MEASURE_UNDERBUST_WIDTH 58

// 60 허리너비
#define POSE2_MEASURE_WAIST_WIDTH 59

// 61 배꼽수준허리너비
#define POSE2_MEASURE_NAVEL_WAIST_WIDTH 60

// 62 배너비
#define POSE2_MEASURE_STOMACH_WIDTH 61

// 63 엉덩이너비
#define POSE2_MEASURE_HIP_WIDTH 62

// 64 넙다리너비
#define POSE2_MEASURE_UNDERHIP_WIDTH 63

// 65 넙다리중간너비
#define POSE2_MEASURE_THIGH_WIDTH 64

// 66 무릎너비
#define POSE2_MEASURE_KNEE_WIDTH 65

// 67 무릎아래너비
#define POSE2_MEASURE_UNDERKNEE_WIDTH 66

// 68 장딴지너비
#define POSE2_MEASURE_CALF_WIDTH 67

// 69 종아리아래너비
#define POSE2_MEASURE_UNDERCALF_WIDTH 68

// 70 위팔너비
#define POSE2_MEASURE_UPPERARM_WIDTH 69

// 71 팔꿈치너비
#define POSE2_MEASURE_ELBOW_WIDTH 70

// 72 손목너비
#define POSE2_MEASURE_WRIST_WIDTH 71

// 73 팔안쪽길이
#define POSE2_MEASURE_ARM_INSIDE_LENGTH 72

// 74 엉덩이옆길이
#define POSE2_MEASURE_HIP_SIDE_LENGTH 73

// 75 허리옆가쪽복사길이
#define POSE2_MEASURE_WAIST_ANKLE_LENGTH 74

// 76 다리가쪽길이
#define POSE2_MEASURE_LEG_LENGTH 75

// 77 몸통세로길이(줄자)
#define POSE2_MEASURE_CONVEX_TORSO_LENGTH 76

// 78 몸통세로길이(체표를 따르는)
#define POSE2_MEASURE_TORSO_LENGTH 77

// 79 젖가슴컵사이즈
#define POSE2_MEASURE_CUP_SIZE 78
